<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<XtiVersion>V23</XtiVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="XTI_Forms" Version="1.8.54-dev251122161951096" />
		<PackageReference Include="XTI_ODataQuery.Api" Version="1.8.54-dev251122161951096" />
		<PackageReference Include="XTI_WebApp.Api" Version="1.8.54-dev251122161951096" />
	</ItemGroup>

</Project>
